<a href="https://colab.research.google.com/github/ferdousahmed11/MMJR-Colab/blob/main/Glucose_level_SimpleLinearRegressionDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#implementation of single linear regression
import numpy as np
import pandas as pd

In [5]:
from google.colab import files 
uploaded=files.upload()

Saving Gluecose-Level-Age.csv to Gluecose-Level-Age (1).csv


In [7]:
df=pd.read_csv('Gluecose-Level-Age.csv')

In [8]:
df

Age  Gluecose-level
0   43              99
1   21              65
2   25              79
3   42              75
4   57              87
5   59              81

In [9]:
df.shape

(6, 2)

In [19]:
x=df[['Age']]
y=df['Gluecose-level']

In [20]:
x

Age
0   43
1   21
2   25
3   42
4   57
5   59

In [21]:
y

0    99
1    65
2    79
3    75
4    87
5    81
Name: Gluecose-level, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split


In [31]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.50,random_state=1)

In [32]:
x_train

Age
0   43
3   42
5   59

In [33]:
x_test

Age
2   25
1   21
4   57

In [34]:
y_train

0    99
3    75
5    81
Name: Gluecose-level, dtype: int64

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
reg=LinearRegression()

In [39]:
reg.fit(x_train,y_train)

LinearRegression()

In [38]:
reg.predict(x_test)

array([91.82417582, 93.01098901, 82.32967033])

In [40]:
y_test

2    79
1    65
4    87
Name: Gluecose-level, dtype: int64

In [42]:
reg.predict([[75]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([76.98901099])

In [43]:
reg.predict([[55]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([82.92307692])

In [44]:
reg.coef_

array([-0.2967033])

In [45]:
reg.intercept_

99.24175824175825

In [ ]:
#y=mx+c