<a href="https://colab.research.google.com/github/ferdousahmed11/MMJR-Colab/blob/main/Predict_Potato_Pricing_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded=files.upload()


Saving PotatoPrice.csv to PotatoPrice.csv


In [3]:
df=pd.read_csv('PotatoPrice.csv')
X=df[['potato_kg']]
Y=df['price']

In [6]:
X


potato_kg
0          1
1          2
2          3
3          4
4          5
5          6
6          7
7          8
8          9
9         10

In [7]:
Y

0     10
1     20
2     25
3     40
4     55
5     75
6     90
7    100
8    115
9    120
Name: price, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.5)

In [9]:
X_test

potato_kg
4          5
9         10
8          9
0          1
1          2

In [10]:
X_train

potato_kg
6          7
7          8
3          4
5          6
2          3

In [11]:
model=tf.keras.Sequential([tf.keras.layers.Dense(1,input_shape=[1],activation='linear')])

In [12]:
Y_test

4     55
9    120
8    115
0     10
1     20
Name: price, dtype: int64

In [13]:
model.compile(optimizer='sgd',loss='mean_squared_error',metrics=['accuracy'])

In [14]:
model.fit(X_train, Y_train, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 592ms/step - loss: 5734.2383 - accuracy: 0.0000e+00
Epoch 2/1000
1/1 [==============================] - 0s 9ms/step - loss: 521.0089 - accuracy: 0.0000e+00
Epoch 3/1000
1/1 [==============================] - 0s 8ms/step - loss: 94.6220 - accuracy: 0.0000e+00
Epoch 4/1000
1/1 [==============================] - 0s 11ms/step - loss: 59.5806 - accuracy: 0.0000e+00
Epoch 5/1000
1/1 [==============================] - 0s 11ms/step - loss: 56.5340 - accuracy: 0.0000e+00
Epoch 6/1000
1/1 [==============================] - 0s 10ms/step - loss: 56.1040 - accuracy: 0.0000e+00
Epoch 7/1000
1/1 [==============================] - 0s 9ms/step - loss: 55.8884 - accuracy: 0.0000e+00
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 55.6912 - accuracy: 0.0000e+00
Epoch 9/1000
1/1 [==============================] - 0s 12ms/step - loss: 55.4961 - accuracy: 0.0000e+00
Epoch 10/1000
1/1 [==============================] - 0s 7ms/step

In [15]:
model.predict(X_test)

1/1 [==============================] - 0s 76ms/step


array([[ 57.329964],
       [132.25671 ],
       [117.27136 ],
       [ -2.611435],
       [ 12.373915]], dtype=float32)

In [18]:
model.predict(Y_test)

1/1 [==============================] - 0s 21ms/step


array([[ 806.5974 ],
       [1780.6451 ],
       [1705.7184 ],
       [ 132.25671],
       [ 282.11023]], dtype=float32)

In [20]:
model.predict([[16]])

1/1 [==============================] - 0s 31ms/step


array([[222.16881]], dtype=float32)

In [21]:
model.predict([[6]])

1/1 [==============================] - 0s 30ms/step


array([[72.31531]], dtype=float32)